const {chromium}=require('./runtime.cjs'),path=require('path');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{const c=await b.newContext({viewport:{width:360,height:740}}),p=await c.newPage();await p.goto(process.env.GAME_URL||'http://127.0.0.1:4173/');await p.getByText('Ready for offline play',{exact:false}).waitFor({timeout:90000});
const shot=async name=>{await p.evaluate(async()=>{
 const urls=new Set([...document.querySelectorAll('*')].map(el=>getComputedStyle(el).backgroundImage).flatMap(value=>[...value.matchAll(/url\(["']?([^"')]+)["']?\)/g)].map(match=>match[1])));
 await Promise.all([...document.images].map(img=>img.decode().catch(()=>{})));
 await Promise.all([...urls].map(async src=>{const img=new Image();img.src=src;await img.decode();}));
 await new Promise(requestAnimationFrame);
});await p.screenshot({path:path.join(__dirname,'../docs/evidence/day-'+name+'.png'),fullPage:true});};
await shot('levels');await p.locator('[data-activity=day]').click();await shot('chooser');await p.locator('[data-chapter=morning]').click();await shot('wake');await p.locator('[data-day-choice=wake]').click();await p.locator('#day-next').click();await p.locator('[data-day-choice=brush]').click();await shot('brush');await p.locator('#day-next').click();await p.locator('[data-day-choice=eat]').click();await shot('breakfast');await p.locator('#day-next').click();await p.locator('[data-day-choice=walk]').click();await p.locator('#day-next').click();await shot('school');await p.setViewportSize({width:1200,height:900});await shot('desktop');await p.setViewportSize({width:360,height:740});await p.locator('#day-back').click();await p.locator('[data-day-hero=cow]').click();await p.locator('[data-chapter=morning]').click();await p.locator('[data-day-choice=wake]').click();await p.locator('#day-next').click();await p.locator('[data-day-choice=brush]').click();await shot('cow-brush');console.log('Saved day visual review screenshots.');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
