const {chromium}=require('./runtime.cjs'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
 const c=await b.newContext({viewport:{width:360,height:740},timezoneId:'Asia/Kolkata'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(process.env.GAME_URL||'http://127.0.0.1:4173/');await p.getByText('Ready for offline play',{exact:false}).waitFor({timeout:90000});await c.setOffline(true);
 const state=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('animal-buddies-v1'))),bookmark=s=>s.journey.bookmarks[s.journey.hero];
 async function parent(){await p.locator('#parent').click();const ns=(await p.locator('label[for=answer]').textContent()).match(/[0-9]+/g).map(Number);await p.locator('#answer').fill(String(ns[0]+ns[1]));await p.locator('#gate button').click();}
 async function restart(){await parent();await p.locator('#new-visit').click();await p.locator('[data-activity=day]').click();}
 assert.equal(await p.locator('.level-card').count(),3);for(const [i,id] of ['names','actions','day'].entries()){const el=p.locator('.level-card').nth(i);assert.equal(await el.getAttribute('data-activity'),id);const box=await el.boundingBox();assert.ok(box.y+box.height<740);}
 await p.locator('[data-activity=day]').click();assert.equal((await state()).session,null,'Browsing does not start timer');await p.locator('[data-day-hero=rabbit]').click();await p.locator('#day-resume').click();
 const deadline=(await state()).session.deadline;assert.equal(bookmark(await state()).node,'wake');
 assert.equal(await p.locator('[data-day-choice]').count(),1,'Wake is an invitation, without a fake wrong choice');await p.locator('[data-day-choice=wake]').click();await p.reload();await p.locator('#day-next').waitFor();assert.equal((await state()).journey.completed['rabbit:wake'],1);await p.locator('#day-next').click();
 assert.equal(bookmark(await state()).node,'brush');await p.locator('[data-day-choice=retry]').click();assert.match(await p.locator('#day-feedback').textContent(),/ball.*toothbrush/);assert.equal(bookmark(await state()).phase,'choose');await p.locator('[data-day-choice=brush]').click();await p.locator('#listen').click();
 await p.waitForTimeout(100);const first=await p.locator('.day-actor .routine-sprite').evaluate(e=>getComputedStyle(e).backgroundPosition);await p.waitForFunction(first=>getComputedStyle(document.querySelector('.day-actor .routine-sprite')).backgroundPosition!==first,first);
 await p.locator('#hint').click();assert.equal(await p.evaluate(()=>document.getAnimations().length),0,'Meaning interrupts motion');
 await p.locator('#library').click();assert.equal((await state()).session.round,2);await p.locator('[data-activity=actions]').click();await p.locator('[data-story-choice]').first().click();await p.locator('#library').click();assert.equal((await state()).session.round,3);assert.equal((await state()).session.deadline,deadline,'Old action level shares budget');
 await p.locator('[data-activity=day]').click();await p.locator('[data-day-hero=cow]').click();await p.locator('#day-resume').click();assert.equal(bookmark(await state()).node,'wake');await p.locator('#day-back').click();await p.locator('[data-day-hero=rabbit]').click();await p.locator('#day-resume').click();assert.equal(bookmark(await state()).node,'brush');assert.equal(bookmark(await state()).phase,'outcome');await p.locator('#day-next').click();assert.equal((await state()).session.round,3,'Revisiting counted outcome does not charge again');
 await p.locator('[data-day-choice=eat]').click();await p.locator('#day-next').click();assert.equal(bookmark(await state()).node,'walk-school');await p.locator('[data-day-choice=walk]').click();await p.locator('#day-next').click();assert.equal(bookmark(await state()).node,'school-hello');assert.ok(await p.locator('.school-hero .routine-sprite').getAttribute('style').then(s=>s.includes('rabbit-routines-v1.png')));
 await p.locator('[data-day-choice=go]').click();await p.locator('[data-day-choice=finish]').click();await p.locator('#day-next').click();await p.getByText('ALL DONE FOR TODAY',{exact:true}).waitFor();assert.equal(bookmark(await state()).node,'school-help','Sixth turn saves next beat before stopping');
 await restart();await p.locator('#day-resume').click();assert.equal(bookmark(await state()).node,'school-help');await p.locator('[data-day-choice=go]').click();await p.reload();await p.locator('[data-day-choice=finish]').waitFor();await p.locator('[data-day-choice=finish]').click();await p.locator('#day-next').click();
 assert.equal(bookmark(await state()).node,'school-water');await p.locator('[data-day-choice=go]').click();await p.locator('[data-day-choice=finish]').click();await p.locator('#day-next').click();assert.equal(bookmark(await state()).node,'walk-home');await p.locator('[data-day-choice=walk]').click();await p.locator('#day-next').click();await p.locator('[data-day-choice=sleep]').click();await p.locator('#day-next').click();await p.locator('#day-resume').waitFor();assert.equal(bookmark(await state()).finished,true);
 await p.locator('[data-day-hero=cow]').click();await p.locator('[data-chapter=morning]').click();assert.equal(bookmark(await state()).node,'wake');await p.locator('[data-day-choice=wake]').click();await p.locator('#day-next').click();await p.locator('[data-day-choice=brush]').click();await p.emulateMedia({reducedMotion:'reduce'});await p.locator('#listen').click();assert.equal(await p.evaluate(()=>document.getAnimations().length),0);
 await p.locator('#day-next').click();await p.getByText('ALL DONE FOR TODAY',{exact:true}).waitFor();await parent();await p.locator('#test-next-day').click();await p.locator('[data-activity=day]').click();await p.locator('#day-resume').click();assert.equal(bookmark(await state()).node,'breakfast');assert.equal((await state()).journey.hero,'cow');
 await p.evaluate(()=>{const s=JSON.parse(localStorage.getItem('animal-buddies-v1'));s.session.deadline=Date.now()-1;localStorage.setItem('animal-buddies-v1',JSON.stringify(s));});await p.reload();await p.getByText('ALL DONE FOR TODAY',{exact:true}).waitFor();assert.equal(bookmark(await state()).node,'breakfast');
 await restart();await p.locator('[data-chapter=school]').click();assert.equal(bookmark(await state()).node,'walk-school');
 // New image and original approved art actually decode offline, not just exist in markup.
 await p.evaluate(async()=>{for(const url of ['./scenes/animal-home-v1.png','./scenes/lakeside-classroom-v2.png','./stories/cow.png','./stories/rabbit.png']){const r=await fetch(url),bitmap=await createImageBitmap(await r.blob());if(!bitmap.width)throw Error(url);bitmap.close();}});
 await parent();await p.locator('#new-visit').click();await p.locator('[data-activity=names]').click();const namesDeadline=(await state()).session.deadline;await p.locator('#library').click();await p.locator('[data-activity=actions]').click();assert.ok((await state()).session.targets.every(id=>['cow','dog','rabbit'].includes(id)),'Cross-level targets must have an existing action sprite');assert.equal((await state()).session.deadline,namesDeadline);
 assert.deepEqual(errors,[]);console.log('PASS day: visible three levels; complete animal-led day; original actions; brush motion/cancel/reduced motion; independent hero checkpoints; same hero across home/school; exact shared budget; reload, restart, next day and timeout; offline artwork.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
