const {chromium}=require('./runtime.cjs'),assert=require('assert/strict'),path=require('path');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
 const url=process.env.GAME_URL||'http://127.0.0.1:4173/';
 const c=await browser.newContext({viewport:{width:360,height:740},userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 26_0 like Mac OS X) AppleWebKit/605.1.15 Version/26.0 Mobile/15E148 Safari/604.1'}),p=await c.newPage(),errors=[];
 p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.getByText('Ready for offline play',{exact:false}).waitFor({timeout:90000});await c.setOffline(true);
 const state=()=>p.evaluate(()=>localStorage.getItem('animal-buddies-v1'));const before=await state();
 assert.equal(await p.locator('.level-card').count(),3);assert.equal(await p.locator('#install-home .install-help').isVisible(),false);
 if(process.env.CAPTURE_VISUALS==='1')await p.screenshot({path:path.join(__dirname,'../docs/evidence/install-chooser.png'),fullPage:true});
 await p.locator('#install-home [data-install]').click();assert.match(await p.locator('#install-home .install-help').innerText(),/Share[\s\S]*Add to Home Screen[\s\S]*Open as Web App/);assert.equal(await state(),before);
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 if(process.env.CAPTURE_VISUALS==='1')await p.screenshot({path:path.join(__dirname,'../docs/evidence/install-iphone-help.png'),fullPage:true});
 await p.locator('#install-home [data-close]').click();await p.locator('#install-home [data-dismiss]').click();assert.equal(await p.locator('#install-home').isVisible(),false);
 await p.locator('[data-activity=names]').click();assert.equal(await p.locator('#install-home').count(),0);await p.locator('#library').click();assert.equal(await p.locator('#install-home').isVisible(),false);
 await p.locator('#parent').click();const numbers=(await p.locator('label[for=answer]').textContent()).match(/[0-9]+/g).map(Number);await p.locator('#answer').fill(String(numbers[0]+numbers[1]));await p.locator('#gate button').click();await p.locator('#install-parent [data-install]').click();assert.equal(await p.locator('#install-parent .install-help').isVisible(),true);await p.locator('#close-parent').click();await p.reload();
 // Simulated browser events test our lifecycle; they do not install an OS app.
 async function offer(outcome,fail=false){await p.evaluate(({outcome,fail})=>{window.promptCalls=0;const event=new Event('beforeinstallprompt',{cancelable:true});event.prompt=()=>{window.promptCalls++;if(fail)throw Error('Browser unavailable');return Promise.resolve();};event.userChoice=Promise.resolve({outcome});window.dispatchEvent(event);},{outcome,fail});}
 const saved=await state();await offer('dismissed');assert.equal(await p.locator('#install-home [data-install]').innerText(),'Install app');await p.locator('#install-home [data-install]').click();await p.getByText(/No problem. You can keep playing/).waitFor();assert.equal(await p.evaluate(()=>window.promptCalls),1);await p.locator('#install-home [data-install]').click();assert.equal(await p.evaluate(()=>window.promptCalls),1);
 await offer('dismissed',true);await p.locator('#install-home [data-install]').click();await p.getByText(/browser could not open installation/).waitFor();
 await offer('accepted');await p.locator('#install-home [data-install]').click();await p.getByText(/Installation requested/).waitFor();assert.equal(await state(),saved);await p.evaluate(()=>dispatchEvent(new Event('appinstalled')));assert.equal(await p.locator('#install-home').isVisible(),false);assert.equal(await state(),saved);assert.deepEqual(errors,[]);await c.close();
 const installed=await browser.newContext();await installed.addInitScript(()=>Object.defineProperty(navigator,'standalone',{value:true}));const ip=await installed.newPage();await ip.goto(url);await ip.locator('.level-card').first().waitFor();assert.equal(await ip.locator('#install-home').isVisible(),false);await installed.close();
 const android=await browser.newContext({userAgent:'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/130.0.0.0 Mobile Safari/537.36'}),ap=await android.newPage();await ap.goto(url);await ap.locator('#install-home [data-install]').click();assert.match(await ap.locator('.install-help').innerText(),/Android[\s\S]*Chrome/);await android.close();
 console.log('PASS: offline iPhone guide, Android fallback, deferred native prompt once, dismissal/retry/error/accepted/install events, standalone hiding, all three levels, parent access and unchanged saves. Browser capabilities simulated; physical phone installation unverified.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
