const {chromium}=require('./runtime.cjs'),assert=require('assert/strict'),path=require('path');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
const c=await b.newContext({viewport:{width:360,height:740}}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto(process.env.GAME_URL||'http://127.0.0.1:4173/');await p.getByText('Ready for offline play',{exact:false}).waitFor({timeout:90000});await c.setOffline(true);
const state=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('animal-buddies-v1')));
async function restart(){await p.locator('#parent').click();const ns=(await p.locator('label[for=answer]').textContent()).match(/[0-9]+/g).map(Number);await p.locator('#answer').fill(String(ns[0]+ns[1]));await p.locator('#gate button').click();await p.locator('#new-visit').click();}
async function shot(name){if(process.env.CAPTURE_VISUALS!=='1')return;await p.evaluate(async()=>{const urls=new Set([...document.querySelectorAll('*')].flatMap(e=>[...getComputedStyle(e).backgroundImage.matchAll(/url\(["']?([^"')]+)["']?\)/g)].map(m=>m[1])));await Promise.all([...document.images].map(i=>i.decode()));await Promise.all([...urls].map(async src=>{const i=new Image();i.src=src;await i.decode();}));});await p.screenshot({path:path.join(__dirname,'../docs/evidence/scene-'+name+'.png'),fullPage:true});}
async function cast(){assert.equal(await p.locator('.school-teacher [data-cast=teacher]').count(),1);assert.equal(await p.locator('.school-classmate').count(),2);assert.equal(await p.locator('.school-classmate [data-cast=cat]').count(),1);assert.equal(await p.locator('.school-classmate [data-cast=duck]').count(),1);assert.equal(await p.locator('.school-prop').count(),0,'Greeting and held-cup outcomes contain no detached prop');}
async function animation(selector){await p.locator('#listen').click();const first=await p.locator(selector).evaluate(e=>getComputedStyle(e).backgroundPosition);await p.waitForFunction(({selector,first})=>getComputedStyle(document.querySelector(selector)).backgroundPosition!==first,{selector,first});await p.locator('#hint').click();assert.equal(await p.evaluate(()=>document.getAnimations().length),0);}
for(const hero of ['cow','rabbit']){
 await restart();await p.locator('[data-activity=day]').click();await p.locator('[data-day-hero='+hero+']').click();await p.locator('[data-chapter=home]').click();await p.locator('[data-day-choice=walk]').click();await p.locator('#day-next').click();
 assert.equal(await p.locator('.bedroom-scene').getAttribute('data-bedding'),'awake');assert.equal(await p.locator('.day-actor').count(),0,'No natural sleep sprite over the blanket');await shot(hero+'-bed-before');await p.locator('[data-day-choice=retry]').click();assert.equal(await p.locator('.bedroom-scene').getAttribute('data-bedding'),'awake');
 await p.locator('[data-day-choice=sleep]').click();const saved=await state();await p.locator('#listen').click();assert.ok(await p.locator('.bedroom-after').evaluate(e=>e.getAnimations().length));await p.locator('#hint').click();assert.equal(await p.evaluate(()=>document.getAnimations().length),0);assert.equal(await p.locator('.bedroom-scene').getAttribute('data-bedding'),'asleep');await shot(hero+'-bed-after');
 await p.reload();await p.locator('#day-next').waitFor();assert.equal((await state()).session.deadline,saved.session.deadline);assert.deepEqual((await state()).journey.completed,saved.journey.completed);assert.equal(await p.locator('.bedroom-after').evaluate(e=>getComputedStyle(e).backgroundPosition),'100% 0%');
 await p.emulateMedia({reducedMotion:'reduce'});await p.locator('#listen').click();assert.equal(await p.evaluate(()=>document.getAnimations().length),0);await p.emulateMedia({reducedMotion:'no-preference'});
 if(hero==='cow'){await p.setViewportSize({width:1200,height:900});await shot('bed-desktop');await p.setViewportSize({width:360,height:740});}
 await restart();await p.locator('[data-activity=day]').click();await p.locator('[data-chapter=morning]').click();assert.equal(await p.locator('.bedroom-scene').getAttribute('data-bedding'),'asleep');assert.match(await p.locator('.bedroom-scene').getAttribute('style'),new RegExp(hero+'-morning-v2'));await p.locator('[data-day-choice=wake]').click();await p.locator('#hint').click();assert.equal(await p.locator('.bedroom-scene').getAttribute('data-bedding'),'greeting');await shot(hero+'-morning');
 await restart();await p.locator('[data-activity=day]').click();await p.locator('[data-chapter=school]').click();await p.locator('[data-day-choice=walk]').click();await p.locator('#day-next').click();await cast();assert.equal(await p.locator('.school-hero').getAttribute('data-actor-hero'),hero);await shot(hero+'-class-prompt');
 await p.locator('[data-day-choice=go]').click();assert.equal(await p.locator('[data-day-choice=finish] .greeting-choice').count(),1,'Choice shows chosen animal waving');await p.locator('[data-day-choice=finish]').click();await cast();assert.equal(await p.locator('.school-hero .routine-sprite').getAttribute('data-pose'),'wave');await animation('.school-hero .routine-sprite');assert.equal(await p.locator('.school-teacher .classroom-sprite').getAttribute('data-pose'),'wave');await shot(hero+'-hello');
 await p.emulateMedia({reducedMotion:'reduce'});await p.locator('#listen').click();assert.equal(await p.evaluate(()=>document.getAnimations().length),0);await p.emulateMedia({reducedMotion:'no-preference'});await p.locator('#day-next').click();
 await p.locator('[data-day-choice=go]').click();await p.locator('[data-day-choice=finish]').click();await p.locator('#hint').click();await shot(hero+'-help');await p.locator('#day-next').click();await p.locator('[data-day-choice=go]').click();assert.equal(await p.locator('.school-hero [data-pose=holding-cup]').count(),1);await p.locator('[data-day-choice=finish]').click();await cast();await animation('.school-hero .drinking-sprite');await shot(hero+'-water');
 if(hero==='cow'){await p.setViewportSize({width:1200,height:900});await shot('class-desktop');await p.setViewportSize({width:360,height:740});}
 // The preserved standalone school uses exactly the same physical scene/effects.
 await restart();await p.locator('[data-activity=day]').click();await p.locator('.day-practice summary').click();await p.locator('#school-entry').click();await p.locator('[data-hero='+hero+']').click();
 for(const mission of ['hello','water']){await p.locator('[data-mission='+mission+']').click();await p.locator('[data-school-choice=go]').click();await p.locator('[data-school-choice=finish]').click();await cast();await animation(mission==='hello'?'.school-hero .routine-sprite':'.school-hero .drinking-sprite');await p.locator('#school-next').click();}
}
await p.evaluate(async()=>{for(const hero of ['cow','rabbit'])for(const room of ['morning','bedtime']){const i=new Image();i.src='./scenes/'+hero+'-'+room+'-v2.png';await i.decode();if(i.naturalWidth!==3*i.naturalHeight)throw Error('Invalid bedroom atlas');}for(const name of ['classroom-cast','school-drinking']){const i=new Image();i.src='./stories/'+name+'-v1.png';await i.decode();if(i.naturalWidth!==1536||i.naturalHeight!==1024)throw Error('Invalid cast atlas');}});
assert.deepEqual(errors,[]);console.log('PASS scenes: both heroes tucked in bed morning/night, own-limb greetings, recognisable teacher and two classmates, held-cup drinking, shared day/practice scenes, finite effects/cancellation/reduced motion, preserved reload receipts/deadlines, six new atlases decoded offline.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
